changed: false
failed: false
gathered:
-   acls:
    -   aces:
        -   grant: deny
            sequence: 10
            source:
                address: 239.0.0.0
                wildcard_bits: 0.255.255.255
        -   grant: permit
            sequence: 20
            source:
                address: any
        acl_type: standard
        name: MULTICAST_SCOPE
    afi: ipv4
