changed: false
failed: false
gathered:
    as_number: '1123'
    bgp:
        log_neighbor_changes: true
    neighbor:
    -   address: 1.1.1.1
        remote_as: 1123
    -   address: 1.1.1.9
        remote_as: 1124
    -   address: 1.2.1.7
        remote_as: 1125
