---
- name: "HIGH | CISC-RT-000130 | PATCH | The Cisco router must be configured to restrict traffic destined to itself."
  block:
    - name: "HIGH | CISC-RT-000130 | PATCH | The Cisco router must be configured to restrict traffic destined to itself. | Remove Old External Access List."
      ios_acls:
          config:
              - afi: ipv4
                acls:
                  - name: "{{ iosrtr_external_acl_name_old }}"
          state: deleted

    - name: "HIGH | CISC-RT-000130 | PATCH | The Cisco router must be configured to restrict traffic destined to itself. | Configure the ACL for any external interfaces."
      ios_acls:
          config:
              - afi: ipv4
                acls:
                - name: "{{ iosrtr_external_acl_name_new }}"
                  acl_type: "{{ iosrtr_external_acl_type }}"
                  aces:
                  - grant: '{{ item.grant | default(omit) }}'
                    sequence: '{{ item.seq | default(omit) }}'
                    log_input: 
                      set: '{{ item.log_input | default(omit) }}'
                    protocol: '{{ item.protocol | default(omit) }}'
                    protocol_options: 
                      tcp:
                        established: '{{ item.protocol_options_tcp_established | default(omit) }}'
                      icmp:
                        echo: '{{ item.protocol_options_icmp_echo | default(omit) }}'
                        echo_reply: '{{ item.protocol_options_icmp_echo_reply | default(omit) }}'
                    source: 
                      any: '{{ item.source_any | default(omit) }}'
                      host: '{{ item.source_host | default(omit) }}'
                      address: '{{ item.source_address | default(omit) }}'
                      wildcard_bits: '{{ item.source_wildcard_bits | default(omit) }}'
                      port_protocol:
                        eq: '{{ item.source_port_protocol_eq | default(omit) }}' 
                    destination:
                      any: '{{ item.destination_any | default(omit) }}'
                      host: '{{ item.destination_host | default(omit) }}'
                      address: '{{ item.destination_address | default(omit) }}'
                      wildcard_bits: '{{ item.destination_wildcard_bits | default(omit) }}'
                      port_protocol:
                        eq: '{{ item.destination_port_protocol_eq | default(omit) }}' 
      with_items: 
          - "{{ iosrtr_external_acl }}"

    - name: "HIGH | CISC-RT-000130 | PATCH | The Cisco router must be configured to restrict traffic destined to itself. | Remove Old Internal Access List"
      ios_acls:
          config:
              - afi: ipv4
                acls:
                  - name: "{{ iosrtr_internal_acl_name_old }}"
          state: deleted

    - name: "HIGH | CISC-RT-000130 | PATCH | The Cisco router must be configured to restrict traffic destined to itself. | Configure the ACL for any internal interfaces."
      ios_acls:
          config:
              - afi: ipv4
                acls:
                - name: "{{ iosrtr_internal_acl_name_new }}"
                  acl_type: "{{ iosrtr_internal_acl_type }}"
                  aces:
                  - grant: '{{ item.grant | default(omit) }}'
                    sequence: '{{ item.seq | default(omit) }}'
                    log_input: 
                      set: '{{ item.log_input | default(omit) }}'
                    protocol: '{{ item.protocol | default(omit) }}'
                    protocol_options: 
                      tcp:
                        established: '{{ item.protocol_options_tcp_established | default(omit) }}'
                      icmp:
                        echo: '{{ item.protocol_options_icmp_echo | default(omit) }}'
                        echo_reply: '{{ item.protocol_options_icmp_echo_reply | default(omit) }}'
                    source: 
                      any: '{{ item.source_any | default(omit) }}'
                      host: '{{ item.source_host | default(omit) }}'
                      address: '{{ item.source_address | default(omit) }}'
                      wildcard_bits: '{{ item.source_wildcard_bits | default(omit) }}'
                      port_protocol:
                        eq: '{{ item.source_port_protocol_eq | default(omit) }}' 
                    destination:
                      any: '{{ item.destination_any | default(omit) }}'
                      host: '{{ item.destination_host | default(omit) }}'
                      address: '{{ item.destination_address | default(omit) }}'
                      wildcard_bits: '{{ item.destination_wildcard_bits | default(omit) }}'
                      port_protocol:
                        eq: '{{ item.destination_port_protocol_eq | default(omit) }}' 
      with_items: 
          - "{{ iosrtr_internal_acl }}"

    - name: "HIGH | CISC-RT-000130 | PATCH | The Cisco router must be configured to restrict traffic destined to itself. | Apply EXTERNAL_ACL to proper interfaces."
      ios_config:
        parents:
          - "interface {{ item }}"
        lines:
          - "ip access-group {{ iosrtr_external_acl_name_new }} in"
      with_items:
        - "{{ iosrtr_external_acl_interfaces }}"

    - name: "HIGH | CISC-RT-000130 | PATCH | The Cisco router must be configured to restrict traffic destined to itself. | Apply INTERNAL_ACL to proper interfaces."
      ios_config:
        parents:
          - "interface {{ item }}"
        lines:
          - "ip access-group {{ iosrtr_internal_acl_name_new }} in"
      with_items:
        - "{{ iosrtr_internal_acl_interfaces }}"
  when:
      - cisc_rt_000130
  tags:
      - CISC-RT-000130
      - CAT1
      - CCI-001097
      - SRG-NET-000205-RTR-000001
      - SV-216561r531085_rule
      - V-216561

- name: "HIGH | CISC-RT-000240 | PATCH | The Cisco perimeter router must be configured to deny network traffic by default and allow network traffic by exception."
  block:
    - name: "HIGH | CISC-RT-000240 | PATCH | The Cisco perimeter router must be configured to deny network traffic by default and allow network traffic by exception. | Search Inbound ACL To Verify That It Is Configured To Deny All Other Traffic That Is Not Explicity Allowed."
      ios_command:
        commands:
          - "show run | section ip access-list extended {{ iosrtr_external_acl_name_new }}"
      register: iosrtr_deny_all_other_traffic
    
    - name: "HIGH | CISC-RT-000240 | PATCH | The Cisco perimeter router must be configured to deny network traffic by default and allow network traffic by exception. | Correct The ACL By Adding Proper Configuration To Deny All Other Traffic That Is Not Explicity Allowed."
      ios_acls:
          config:
              - afi: ipv4
                acls:
                - name: "{{ iosrtr_external_acl_name_new }}"
                  acl_type: "{{ iosrtr_external_acl_type }}"
                  aces:
                  - grant: deny
                    sequence: 200
                    log_input: 
                      set: true
                    protocol: ip 
                    source: 
                      any: true
                    destination:
                      any: true
      when: "'deny   ip any any log-input' not in iosrtr_deny_all_other_traffic"
  when:
      - cisc_rt_000240
      - not cisc_rt_dodin_backbone
  tags:
      - CISC-RT-000240
      - CAT1
      - CCI-001109
      - SRG-NET-000202-RTR-000001
      - SV-216572r531085_rule
      - V-216572

- name: "HIGH | CISC-RT-000280 | PATCH | The Cisco perimeter router must be configured to protect an enclave connected to an alternate gateway by using an inbound filter that only permits packets with destination addresses within the sites address space."
  block:
    - name: "HIGH | CISC-RT-000280 | PATCH | The Cisco perimeter router must be configured to protect an enclave connected to an alternate gateway by using an inbound filter that only permits packets with destination addresses within the sites address space. | Rmmove Old FILTER_ISP Access Control Lost."
      ios_acls:
          config:
              - afi: ipv4
                acls:
                  - name: "{{ iosrtr_filter_isp_name_old }}"
          state: deleted

    - name: "HIGH | CISC-RT-000280 | PATCH | The Cisco perimeter router must be configured to protect an enclave connected to an alternate gateway by using an inbound filter that only permits packets with destination addresses within the sites address space. | Configure The New Ingress ACL For FILTER_ISP."
      ios_acls:
          config:
              - afi: ipv4
                acls:
                - name: "{{ iosrtr_filter_isp_acl_name_new }}"
                  acl_type: "{{ iosrtr_filter_isp_acl_type }}"
                  aces:
                  - grant: '{{ item.grant | default(omit) }}'
                    sequence: '{{ item.seq | default(omit) }}'
                    log_input: 
                      set: '{{ item.log_input | default(omit) }}'
                    protocol: '{{ item.protocol | default(omit) }}'
                    protocol_options: 
                      tcp:
                        established: '{{ item.protocol_options_tcp_established | default(omit) }}'
                      icmp:
                        echo: '{{ item.protocol_options_icmp_echo | default(omit) }}'
                        echo_reply: '{{ item.protocol_options_icmp_echo_reply | default(omit) }}'
                    source: 
                      any: '{{ item.source_any | default(omit) }}'
                      host: '{{ item.source_host | default(omit) }}'
                      address: '{{ item.source_address | default(omit) }}'
                      wildcard_bits: '{{ item.source_wildcard_bits | default(omit) }}'
                      port_protocol:
                        eq: '{{ item.source_port_protocol_eq | default(omit) }}' 
                    destination:
                      any: '{{ item.destination_any | default(omit) }}'
                      host: '{{ item.destination_host | default(omit) }}'
                      address: '{{ item.destination_address | default(omit) }}'
                      wildcard_bits: '{{ item.destination_wildcard_bits | default(omit) }}'
                      port_protocol:
                        eq: '{{ item.destination_port_protocol_eq | default(omit) }}' 
      with_items: 
          - "{{ iosrtr_filter_isp_acl }}"

    - name: "HIGH | CISC-RT-000280 | PATCH | The Cisco perimeter router must be configured to protect an enclave connected to an alternate gateway by using an inbound filter that only permits packets with destination addresses within the sites address space. | Attach FILTER_ISP to Inbound Interface and Add Description."
      ios_config:
        parents:
          - "interface {{ item }}"
        lines:
          - description {{ iosrtr_filter_isp_interface_description }}
          - "ip access-group {{ iosrtr_filter_isp_acl_name_new }} in"
      with_items:
        - "{{ iosrtr_filter_isp_acl_interfaces }}"
  when:
      - cisc_rt_000280
      - not cisc_rt_dodin_backbone
  tags:
      - CISC-RT-000280
      - CAT1
      - CCI-001414
      - SRG-NET-000019-RTR-000008
      - SV-216576r531085_rule
      - V-216576

- name: "HIGH | CISC-RT-000290 | PATCH | The Cisco perimeter router must be configured to not be a Border Gateway Protocol (BGP) peer to an alternate gateway service provider."
  block:
    - name: Verify that the router is not BGP peering with this router.
      ios_command:
          commands:
            - "show run | section include bgp"
      register: iosrtr_bgp_peering_with_alterrnate_gateway_service_provider

    - name: "HIGH | CISC-RT-000290 | PATCH | The Cisco perimeter router must be configured to not be a Border Gateway Protocol (BGP) peer to an alternate gateway service provider. | Set Fact For Neighbor Ip Addresses."
      set_fact:
          list: "{{ iosrtr_bgp_peering_with_alterrnate_gateway_service_provider.stdout_lines | regex_findall('((?:[0-9]{1,3}.){3}[0-9]{1,3})') }}"

    - name: "HIGH | CISC-RT-000290 | PATCH | The Cisco perimeter router must be configured to not be a Border Gateway Protocol (BGP) peer to an alternate gateway service provider. | Add Static Route If It Is BGP Peering With Provider."
      ios_static_routes:
          config:
          - address_families:
            - afi: ipv4
              routes:
                - dest: 0.0.0.0/0
                  next_hops:
                    - forward_router_address: "{{ item }}"
      with_items:
        - "{{ iosrtr_isp_router_ip_address }}"
      when: item in list
      
    - name: "HIGH | CISC-RT-000290 | PATCH | The Cisco perimeter router must be configured to not be a Border Gateway Protocol (BGP) peer to an alternate gateway service provider. | Remove any BGP Peering neighbors from configuration."
      ios_config:
          parents:
            - "router bgp {{ iosrtr_local_bgp_autonomous_system_number }}"
          lines:
            - "no neighbor {{ item }}"
      with_items:
        - "{{ iosrtr_isp_router_ip_address }}"
      when: item in list
  when:
      - cisc_rt_000290
      - not cisc_rt_dodin_backbone
  tags:
      - CISC-RT-000290
      - CAT1
      - CCI-001414
      - SRG-NET-000019-RTR-000009
      - SV-216577r531085_rule
      - V-216577

- name: "HIGH | CISC-RT-000630 | PATCH | The Cisco PE router must be configured to have each Virtual Routing and Forwarding (VRF) instance bound to the appropriate physical or logical interfaces to maintain traffic separation between all MPLS L3VPNs."
  debug:
    msg: "test" 
  when:
      - cisc_rt_000630
  tags:
      - CISC-RT-000630
      - CAT1
      - CCI-000366
      - SRG-NET-000512-RTR-000005
      - SV-216611r531085_rule
      - V-216611

- name: "HIGH | CISC-RT-000640 | PATCH | The Cisco PE router must be configured to have each Virtual Routing and Forwarding (VRF) instance with the appropriate Route Target (RT)."
  debug:
    msg: "test"  
  when:
      - cisc_rt_000640
  tags:
      - CISC-RT-000640
      - CAT1
      - CCI-000366
      - SRG-NET-000512-RTR-000006
      - SV-216612r531085_rule
      - V-216612

- name: "HIGH | CISC-RT-000670 | PATCH | The Cisco PE router providing MPLS Virtual Private Wire Service (VPWS) must be configured to have the appropriate virtual circuit identification (VC ID) for each attachment circuit."
  debug:
    msg: "test"  
  when:
      - cisc_rt_000670
  tags:
      - CISC-RT-000670
      - CAT1
      - CCI-000366
      - SRG-NET-000512-RTR-000008
      - SV-216615r531085_rule
      - V-216615

- name: "HIGH | CISC-RT-000730 | PATCH | The Cisco PE router must be configured to block any traffic that is destined to IP core infrastructure."
  debug:
    msg: "test"  
  when:
      - cisc_rt_000730
  tags:
      - CISC-RT-000730
      - CAT1
      - CCI-001097
      - SRG-NET-000205-RTR-000007
      - SV-216616r531085_rule
      - V-216616

- name: "HIGH | CISC-RT-000310 | PATCH | The Cisco PE router must be configured to block any traffic that is destined to IP core infrastructure."
  debug:
    msg: "test"  
  when:
      - cisc_rt_000310
      - not cisc_rt_dodin_backbone
  tags:
      - CISC-RT-000310
      - CAT1
      - CCI-001094
      - SRG-NET-000205-RTR-000014
      - SV-216989r531085_rule
      - V-216989









- name: Gather static routes
  block:
    - name: Use the Prefix Lists resource module to gather the current config
      ios_static_routes:
        config:
        state: gathered
      register: ios_static_routes

    - name: Print Static Routes To Screen
      debug:
        msg: "{{ ios_static_routes }}"

    - name: Create Inventory Directory
      file:
        path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
        state: directory

    - name: Write Static Routes Configuration to File
      copy:
        content: "{{ ios_static_routes | to_nice_yaml }}"
        dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/static_routes.yaml"
  when:
      - cisc_rt_static_routes






- name: Gather Acl Facts
  block:
    - name: Use the ACLs resource module to gather the current config
      ios_acls:
        state: gathered
      register: acls 

    - name: Print ACLs To Screen
      debug:
        msg: "{{ acls }}"

    - name: Create Inventory Directory
      file:
        path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
        state: directory

    - name: Write ACL Configuration to File
      copy:
        content: "{{ acls | to_nice_yaml }}"
        dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/acls.yaml"
  when:
      - cisc_rt_acl


- name: Gather BGP Facts
  block:
    - name: Use the bgps resource module to gather the current config
      ios_bgp_global:
        config:
        state: gathered
      register: bgps

    - name: Print bgps To Screen
      debug:
        msg: "{{ bgps }}"

    - name: Create Inventory Directory
      file:
        path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
        state: directory

    - name: Write bgp Configuration to File
      copy:
        content: "{{ bgps | to_nice_yaml }}"
        dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/bgp.yaml"
  when:
      - cisc_rt_bgp


- name: Gather Route Maps Facts
  block:
    - name: Use the Route Maps resource module to gather the current config
      ios_route_maps:
        config:
        state: gathered
      register: route_maps

    - name: Print Route Maps To Screen
      debug:
        msg: "{{ route_maps }}"

    - name: Create Inventory Directory
      file:
        path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
        state: directory

    - name: Write Route Maps Configuration to File
      copy:
        content: "{{ route_maps | to_nice_yaml }}"
        dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/route_maps.yaml"
  when:
      - cisc_rt_route_maps



- name: Gather Prefix Lists Facts
  block:
    - name: Use the Prefix Lists resource module to gather the current config
      ios_prefix_lists:
        config:
        state: gathered
  when:
      - cisc_rt_prefix_lists

- name: Gather ospf roesources Facts
  block:
    - name: Use the ospf interfaces resource module to gather the current config
      ios_ospfv2:
        config:
        state: gathered
      register: ios_ospfv2

    - name: Print ospf interfaces To Screen
      debug:
        msg: "{{ ios_ospfv2 }}"

    - name: Create Inventory Directory
      file:
        path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
        state: directory

    - name: Write ospf_resources Configuration to File
      copy:
        content: "{{ ios_ospfv2 | to_nice_yaml }}"
        dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/ios_ospf_interfaces.yaml"
  when:
      - cisc_rt_ospf_maps


