---
- name: Include CAT 1 patches
  import_tasks: fix-cat1.yml
  when: iosrtrstig_cat1_patch
  tags:
      - CAT1
      - high

- name: Include CAT 2 patches
  import_tasks: fix-cat2.yml
  when: iosrtrstig_cat2_patch
  tags:
      - CAT2
      - medium

- name: Include CAT 3 patches
  import_tasks: fix-cat3.yml
  when: iosrtrstig_cat3_patch
  tags:
      - CAT3
      - low
 
- name: If Warnings found Output count and control IDs affected
  debug:
    msg: 
      - "You have {{ warn_count }} Warning(s) that require investigating that are related to the following STIG Controls:"
      - "{{ control_number }}"
  when: warn_count != 0
  tags:
      - always

  