changed: false
failed: false
gathered:
-   acls:
    -   aces:
        -   destination:
                any: true
            grant: deny
            log:
                set: true
            protocol: ip
            sequence: 10
            source:
                any: true
        acl_type: extended
        name: INGRESS_FILTER
    afi: ipv4
